easy_admin:
    site_name: 'ADMINATOR EL DOMINATOR'
    design:
        assets:
            css:
                - 'css/admin.css'
        brand_color: 'rgb(176,33,26)'
        menu:
            - { label: 'Entités'}
            - { entity: 'Project', label: 'Projets'}
            - { entity: 'City', label: 'Villes'}
            - { entity: 'Category', label: 'Catégories'}
            - { entity: 'User', label: 'Utilisateurs'}
            - { entity: 'Comment', label: 'Modération'}
            - { label : 'Liens'}
            - { label: 'Retour au site', route: 'homepage' }

    entities:
#        # List the entity class name you want to manage
        City:
            class: App\Entity\City
            image_base_path: '%uploads_url%/cities'
            form:
                fields:
                    - 'name'
                    - { property: 'picturePath', type: 'file_upload', type_options: { upload_dir: 'public/uploads/cities' } }
            list:
                fields:
                    - 'id'
                    - 'name'
                    - {property: 'picture', type: 'image'}
                    - 'projects'
        Project:
            class: App\Entity\Project
            disabled_actions: ['edit']
            image_base_path: '%uploads_url%/projects'
            form:
                fields:
                    - 'title'
                    - { property: 'picture', type: 'file', upload_dir: 'public/uploads/projects' }
                    - { property: 'cost', type: 'money', type_options: { currency: 'EUR' } }
                    - 'excerpt'
                    - 'description'
            list:
                fields:
                    - 'title'
                    - 'cost'
                    - 'excerpt'
                    - 'createdAt'
                    - {property: 'picture', type: 'image'}

        Category:
            class: App\Entity\Category
            form:
                fields:
                    - 'label'

        User:
            class: App\Entity\User
            form:
                fields:
                    - { property: 'email', type: 'email'}
                    - 'firstname'
                    - 'lastname'

        Comment:
            class: App\Entity\Comment
            disabled_actions: ['new']
            form:
                fields:
                    - 'title'
                    - 'content'